server:
  port: 9080
security:
  oauth2:
    client:
      # From OIDC app
      clientId: 0oadshsatx30m3xs70h7
      clientSecret: Kg8hlVZHvoHgazz5mxUvoZNESikyec7KByzO_aCN
      # From Authorization Server's metadata
      accessTokenUri: https://dev-197645.oktapreview.com/oauth2/default/v1/token
      userAuthorizationUri: https://dev-197645.oktapreview.com/oauth2/default/v1/authorize
      clientAuthenticationScheme: form
      scope: openid profile email
    resource:
      # from your Auth Server's metadata, check .well-known/openid-configuration
      # if not in .well-known/oauth-authorization-server
      userInfoUri: https://dev-197645.oktapreview.com/oauth2/default/v1/userinfo