# AzzureApp Microservice
---
# AzzureApp Microservice
apiVersion: v1
data:
  AZ_CLIENT_SERVER_PORT: "7080"
  RABBITMQ_HOST: "rabbitmq-svc"
  RABBITMQ_PORT: "5672"
  AZURE_MS_HOST: "azureappserver-svc"
  AZURE_MS_PORT: "7081"  
kind: ConfigMap
metadata:
  name: azureappclient-ms-config
---
apiVersion: v1
kind: Service
metadata:
  name: azureappclient-svc
spec:
  ports:
  - port: 7080
    targetPort: 7080
  selector:
    app: azureappclient
---
apiVersion: apps/v1beta1 
kind: Deployment
metadata:
  name: azureappclient-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: azureappclient
    spec:
      containers:
      - name: azureappclient-container
        image: pandyamitesh/azureappclient:0.0.1-SNAPSHOT
        imagePullPolicy: Always       
        ports:
        - containerPort: 7080
          protocol: "TCP"    
---
apiVersion: v1
kind: Service
metadata:
  name: azureappclient-nodeport
spec:
  type: NodePort
  ports:
  - port: 7080
    targetPort: 7080
    nodePort: 30780
    name: az-http  
  selector:
    app: azureappclient
---
apiVersion: v1
kind: Service
metadata:
  name: azureappclient-lb
spec:
  type: LoadBalancer
  ports:
  - port: 32766
    targetPort: 7080
    name: az-lb  
  selector:
    app: azureappclient